# Hungarian translation for testdrive
# Copyright (c) 2010 Rosetta Contributors and Canonical Ltd 2010
# This file is distributed under the same license as the testdrive package.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2010.
#
msgid ""
msgstr ""
"Project-Id-Version: testdrive\n"
"Report-Msgid-Bugs-To: FULL NAME <EMAIL@ADDRESS>\n"
"POT-Creation-Date: 2013-08-02 08:14+1000\n"
"PO-Revision-Date: 2010-09-15 11:44+0000\n"
"Last-Translator: Richard Somlói <ricsipontaz@gmail.com>\n"
"Language-Team: Hungarian <hu@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Launchpad-Export-Date: 2013-08-10 20:12+0000\n"
"X-Generator: Launchpad (build 16723)\n"

#: ../testdrive-gtk.desktop.in.h:1
msgid "Test Drive an Ubuntu ISO"
msgstr "Ubuntu-lemezképek tesztelése"

#: ../testdrive-gtk.desktop.in.h:2
msgid "Download and run an Ubuntu ISO in a Virtual Machine"
msgstr "Ubuntu-lemezképek letöltése, és futtatása virtuális gépben"

#: ../testdrive-gtk.desktop.in.h:3
msgid "ISO;Testing;Ubuntu;Daily;VM;Virtual Machine;zsync;rsync;Testdrive"
msgstr ""

#: ../bin/testdrive-gtk.py:49
msgid "Other"
msgstr "Egyéb"

#. ##################################################################
#. ####### Obtaining the settings from the Preferences Class ########
#. ##################################################################
#: ../bin/testdrive-gtk.py:139
msgid "Instancing Preferences..."
msgstr "Beállítások betöltése…"

#: ../bin/testdrive-gtk.py:222
#, python-format
msgid ""
"Checking available ISOs at the ISO tracker [http://iso.qa.ubuntu.com] every "
"%s seconds"
msgstr ""

#: ../bin/testdrive-gtk.py:227
msgid "Unable to check the ISO tracker"
msgstr ""

#: ../bin/testdrive-gtk.py:265
#, python-format
msgid "<b>Release:</b> %s"
msgstr "<b>Kiadás:</b> %s"

#: ../bin/testdrive-gtk.py:266
#, python-format
msgid "<b>ISO Repository:</b> http://%s.ubuntu.com/"
msgstr "<b>Lemezkép tároló:</b> http://%s.ubuntu.com/"

#: ../bin/testdrive-gtk.py:306
msgid "Add an ISO to TestDrive"
msgstr "Lemezkép hozzáadása teszteléshez"

#: ../bin/testdrive-gtk.py:322
msgid ""
"Unable to open because 'testdrive' is not installed.\n"
"Please install testdrive: \n"
"\n"
"sudo apt-get install testdrive-cli"
msgstr ""
"A megnyitás nem sikerült. Nincs telepítve a „testdrive” csomag\n"
"Telepítse a következő paranccsal: \n"
"\n"
"sudo apt-get install testdrive-cli"

#: ../bin/testdrive-gtk.py:326
msgid "TestDrive an ISO or Disk Image"
msgstr "Lemezkép tesztelése"

#. ##################################################################
#. ## Obtains the command for the Sync process based on Protocol ####
#. ##################################################################
#: ../bin/testdrive-gtk.py:401
msgid "Obtaining the sync protocol for the specified ISO..."
msgstr "Szinkronizáló protokoll betöltése…"

#: ../bin/testdrive-gtk.py:404 ../bin/testdrive.py:375
#, python-format
msgid "Unsupported protocol [%s]"
msgstr "Nem támogatott protokoll: [%s]"

#. ##################################################################
#. #### Obtains the Virtualization Method, if not shows warnings ####
#. ##################################################################
#. Choose the virtualization engine
#: ../bin/testdrive-gtk.py:415
msgid "Obtaining the virtualization method..."
msgstr "Virtualizációs módszer betöltése…"

#: ../bin/testdrive-gtk.py:419
msgid "Your CPU supports KVM acceleration; please install KVM"
msgstr "A processzora támogatja a KVM gyorsítást, telepítse a KVM csomagot"

#: ../bin/testdrive-gtk.py:420
msgid ""
"Your CPU supports KVM acceleration; please install KVM:\n"
"\n"
"sudo apt-get install qemu-kvm"
msgstr ""
"A processzora támogatja a KVM gyorsítás, telepítse a KVM csomagot:\n"
"\n"
"sudo apt-get install qemu-kvm"

#: ../bin/testdrive-gtk.py:424
msgid ""
"Your CPU does not support acceleration; run kvm-ok for more information; "
"then install VBox"
msgstr ""
"A processzora nem támogatja a gyorsítást, futtassa a kvm-ok parancsot "
"további információért; majd telepítse a VBox csomagot"

#: ../bin/testdrive-gtk.py:425
msgid ""
"Your CPU does not support acceleration; run kvm-ok for more information;\n"
"then please install VirtualBox\n"
"\n"
"kvm-ok\n"
"sudo apt-get install virtualbox-ose"
msgstr ""
"A processzora nem támogatja a gyorsítást, futtassa a kvm-ok parancsot "
"további információért, majd telepítse a VBox-ot\n"
"\n"
"kvm-ok\n"
"sudo apt-get install virtualbox-ose"

#. ##################################################################
#. ### Obtains the list of ISO available from the iso list cache ####
#. ##################################################################
#. Try to retrieve the ISO list from the cache
#: ../bin/testdrive-gtk.py:438 ../bin/testdrive.py:348
msgid "Retrieving the Ubuntu ISO list from cache..."
msgstr "Az Ubuntu-lemezképek listájának betöltése a gyorsítótárból…"

#: ../bin/testdrive-gtk.py:442 ../bin/testdrive-gtk.py:443
#: ../bin/testdrive.py:352
msgid "Unable to retrieve the Ubuntu ISO list from cache..."
msgstr ""
"Az Ubuntu-lemezképek listájának betöltése a gyorsítótárból nem sikerült…"

#: ../bin/testdrive-gtk.py:563 ../bin/testdrive-gtk.py:598
#: ../bin/testdrive-gtk.py:905
#, python-format
msgid "<i>     CACHE: [%s]</i>"
msgstr "<i> GYORSÍTÓTÁR: [%s]</i>"

#: ../bin/testdrive-gtk.py:565 ../bin/testdrive-gtk.py:600
#: ../bin/testdrive-gtk.py:907
msgid "<i>     CACHE: [empty]</i>"
msgstr "<i> GYORSÍTÓTÁR: [üres]</i>"

#: ../bin/testdrive-gtk.py:628
msgid "<b><i>There are no Other ISOs yet...</i></b>"
msgstr "<b><i>Jelenleg nincsenek további lemezképek megadva…</i></b>"

#: ../bin/testdrive-gtk.py:631
msgid "<b><i>There are no ISOs for this architecture yet...</i></b>"
msgstr ""
"<b><i>Jelenleg nincsenek lemezképek ehhez az architektúrához…</i></b>"

#. Add Button
#: ../bin/testdrive-gtk.py:665
msgid "Add ISO"
msgstr "Lemezkép hozzáadása"

#. Create Buttons
#: ../bin/testdrive-gtk.py:672
msgid "Create USB Disk"
msgstr "USB indítólemez készítése"

#: ../bin/testdrive-gtk.py:677
msgid "Sync"
msgstr "Szinkronizálás"

#: ../bin/testdrive-gtk.py:682
msgid "Launch"
msgstr "Futtatás"

#: ../bin/testdrive-gtk.py:736 ../bin/testdrive.py:264
msgid "Using KVM for virtual machine hosting..."
msgstr "KVM használata a virtualizációhoz…"

#: ../bin/testdrive-gtk.py:739 ../bin/testdrive.py:266
msgid "Using VirtualBox for virtual machine hosting..."
msgstr "VirtualBox használata a virtualizációhoz…"

#: ../bin/testdrive-gtk.py:742 ../bin/testdrive.py:268
msgid "Using Parallels Desktop for virtual machine hosting..."
msgstr "Parallels Desktop használata a virtualizációhoz…"

#: ../bin/testdrive-gtk.py:796
msgid "sync_iso: Thread is executing..."
msgstr "sync_iso: A szál fut…"

#: ../bin/testdrive-gtk.py:817
msgid "launch_iso: Thread is executing or syncing..."
msgstr "launch_iso: A szál fut vagy végrehajtás alatt áll…"

#: ../bin/testdrive-gtk.py:824
msgid ""
"No ISO has been selected.\n"
"\n"
"Please select an ISO to create an USB Startup Disk."
msgstr ""
"Nincs lemezkép kiválasztva.\n"
"\n"
"Válasszon egy lemezképet az USB indítólemez létrehozásához."

#: ../bin/testdrive-gtk.py:829
msgid ""
"More than 1 ISO has been selected.\n"
"\n"
"Please select only 1 ISO to continue!"
msgstr ""
"Több, mint egy lemezkép van kiválasztva.\n"
"\n"
"Csak egyet válaszon a folytatáshoz!"

#: ../bin/testdrive-gtk.py:834
msgid ""
"The specified ISO does not exist!\n"
"\n"
"Please, synchronize the ISO to continue."
msgstr ""
"A megadott lemezkép nem létezik!\n"
"\n"
"Szinkronizálja a folytatáshoz."

#: ../bin/testdrive-gtk.py:841
msgid "Unable to launch USB Creator!"
msgstr "Az USB indítólemez-készítő indítása meghiúsult!"

#: ../bin/testdrive-gtk.py:867
#, python-format
msgid " Downloading %s (0%%)"
msgstr ""

#: ../bin/testdrive-gtk.py:887
#, python-format
msgid " Downloading %s (%s%%)"
msgstr ""

#: ../bin/testdrive-gtk.py:936
msgid "    Configuring Virtual Machine..."
msgstr ""

#: ../bin/testdrive-gtk.py:942
msgid "     Running Virtual Machine..."
msgstr ""

#: ../bin/testdrive-gtk.py:991
msgid "Show debug messages"
msgstr "Hibakeresési üzenetek megjelenítése"

#: ../bin/testdrive.py:52
msgid ""
"\n"
"Welcome to Testdrive!\n"
msgstr ""
"\n"
"Üdvözöljük a Testdrive alkalmazásban!\n"

#: ../bin/testdrive.py:60
#, python-format
msgid "     +-cache--> [%s] %s"
msgstr "     +-gyorsítótár--> [%s] %s"

#: ../bin/testdrive.py:63
#, python-format
msgid "  %d. Other (prompt for ISO URL)"
msgstr "  %d. Egyéb (megadott elérési útvonalról)"

#: ../bin/testdrive.py:65
msgid ""
"\n"
"Select an image to testdrive [1]: "
msgstr ""
"\n"
"Képfájl kiválasztása teszteléshez [1]: "

#: ../bin/testdrive.py:74
msgid ""
"\n"
"ERROR: Invalid input\n"
msgstr ""
"\n"
"HIBA: Érvénytelen bemenet\n"

#: ../bin/testdrive.py:77
msgid ""
"\n"
"Enter an ISO URL to testdrive: "
msgstr ""
"\n"
"Adja meg a tesztelni kívánt képfájl elérési címét: "

#: ../bin/testdrive.py:84
msgid ""
"\n"
"ERROR: Invalid selection\n"
msgstr ""
"\n"
"HIBA: Érvénytelen kiválasztás\n"

#: ../bin/testdrive.py:88
#, python-format
msgid ""
"\n"
"%s\n"
msgstr ""

#: ../bin/testdrive.py:102 ../testdrivegtk/AddOtherTestdrivegtkDialog.py:155
#, python-format
msgid "Invalid ISO URL [%s]"
msgstr "Érvénytelen lemezkép elérési cím: [%s]"

#: ../bin/testdrive.py:144
#, python-format
msgid ""
"Command failed\n"
"    `%s`"
msgstr ""
"Parancs hiba\n"
"    `%s`"

#: ../bin/testdrive.py:151
msgid "Launching Virtual Machine using CURSES as screen mode"
msgstr ""

#: ../bin/testdrive.py:196
msgid "user configuration file (overriding default values"
msgstr "saját beállítófájl (felülírja az alapértelmezett beállításokat"

#: ../bin/testdrive.py:198
msgid "print version and system data, and exit"
msgstr "verzió és rendszer információk kiírása, majd kilépés"

#: ../bin/testdrive.py:200
msgid "get ISO image from this URL location"
msgstr "Lemezkép letöltése a megadott címről"

#: ../bin/testdrive.py:202
msgid "try to launch usb-creator for further testing"
msgstr ""
"próbálja meg elindítani az usb-creator alkalmazást  a további tesztekhez"

#: ../bin/testdrive.py:204
msgid "hardcode Ubuntu RELEASE codename"
msgstr "Az Ubuntu KIADÁS kódneve"

#: ../bin/testdrive.py:206
msgid ""
"hardcode Ubuntu flavor. Available Flavors:\n"
"             "
"ubuntu/kubuntu/xubuntu/edubuntu/mythbuntu/ubuntustudio/lubuntu/ubuntukylin"
msgstr ""

#: ../bin/testdrive.py:209
msgid ""
"hardcode Ubuntu repository from where to obtain ISOs:\n"
"             releases/cdimage/cloud-daily/cloud-releases"
msgstr ""

#: ../bin/testdrive.py:212
msgid ""
"displays the Virtual Machine in the shell. Only valid for Cloud images."
msgstr ""

#: ../bin/testdrive.py:217
#, python-format
msgid "version passed: %s"
msgstr "Verzió megállapítva: %s"

#: ../bin/testdrive.py:221
#, python-format
msgid "testdrive %s"
msgstr "testdrive %s"

#: ../bin/testdrive.py:233
#, python-format
msgid "config passed: %s"
msgstr "A konfiguráció megállapítva: %s"

#: ../bin/testdrive.py:243
#, python-format
msgid "Trying config in %s"
msgstr "Konfiguráció kipróbálása: %s"

#: ../bin/testdrive.py:247
#, python-format
msgid "Using configuration in %s"
msgstr "Konfiguráció használata: %s"

#: ../bin/testdrive.py:249
#, python-format
msgid "Invalid configuration [%s]"
msgstr "Érvénytelen konfiguráció [%s]"

#: ../bin/testdrive.py:257
msgid ""
"Your CPU supports KVM acceleration; please install KVM:\n"
"            sudo apt-get install qemu-kvm"
msgstr ""

#: ../bin/testdrive.py:260
msgid ""
"Your CPU does not support acceleration; run kvm-ok for more information; "
"then please install VirtualBox:\n"
"            kvm-ok\n"
"            sudo apt-get install virtualbox-ose"
msgstr ""

#: ../bin/testdrive.py:284
msgid ""
"Launching Cloud images only works with KVM. Please switch your "
"virtualization method..."
msgstr ""

#: ../bin/testdrive.py:335
#: ../testdrivegtk/PreferencesTestdrivegtkDialog.py:333
#, python-format
msgid "Obtaining Ubuntu ISO list from %s..."
msgstr "Az Ubuntu-lemezképek listájának letöltése a következő helyről: %s…"

#: ../bin/testdrive.py:339
#, python-format
msgid "ERROR: Could not obtain the Ubuntu ISO list from %s..."
msgstr ""
"Az Ubuntu-lemezképek listájának letöltése sikertelen a következő helyről: %s…"

#: ../bin/testdrive.py:345
#: ../testdrivegtk/PreferencesTestdrivegtkDialog.py:345
msgid "Unable to update the Ubuntu ISO list cache..."
msgstr "Az Ubuntu-lemezképek listájának gyorsítótár frissítése nem sikerült…"

#. BUG: should check disk space availability in CACHE dir
#. Update the cache
#: ../bin/testdrive.py:371
msgid "Syncing the specified ISO..."
msgstr "A megadott lemezkép szinkronizálása…"

#: ../bin/testdrive.py:378 ../testdrivegtk/AddOtherTestdrivegtkDialog.py:167
#, python-format
msgid "ISO not found at [%s]"
msgstr "A lemezkép nem található a megadott helyen: [%s]"

#. ##################
#. # Launch the VM ##
#. ##################
#: ../bin/testdrive.py:401
msgid "Validating Virtualization Method...."
msgstr "Virtualizációs módszer érvényesítése…"

#: ../bin/testdrive.py:405
#, python-format
msgid "Unable to validate Virtualization Method [%s]"
msgstr "A virtualizációs módszer érvényesítése nem sikerült: [%s]"

#: ../bin/testdrive.py:407
msgid "Setting up Virtual Machine..."
msgstr "Virtuális gép beállítása…"

#: ../bin/testdrive.py:411
msgid "Unable to setup Virtual Machine"
msgstr "A virtuális gép beállítása nem sikerült"

#: ../bin/testdrive.py:413
msgid "Launching Virtual Machine..."
msgstr "Virtuális gép indítása…"

#: ../bin/testdrive.py:421
msgid "Unable to launch Virtual Machine"
msgstr "A virtuális gép indítása sikertelen"

#: ../bin/testdrive.py:425
#, python-format
msgid "Cleaning up disk image [%s]..."
msgstr "Lemez tisztása [%s]…"

#. Remind about cache cleanup
#: ../bin/testdrive.py:428
msgid "You may wish to clean up the cache directory..."
msgstr "A gyorsítótárként használt könyvtárak tisztítása…"

#: ../bin/testdrive.py:429
#, python-format
msgid "      %s and %s"
msgstr "      %s és %s"

#: ../bin/testdrive.py:436
msgid ""
"\n"
"Launch USB Startup Disk Creator for further testing of this ISO? [y/N] "
msgstr ""
"\n"
"Kívánja az USB indtólemez-készítőt elindítani további teszteléshez? [y/N] "

#: ../bin/testdrive.py:440
msgid ""
"\n"
"Press <enter> to exit..."
msgstr ""
"\n"
"Nyomjon <entert>-t a kilépéshez…"

#: ../testdrivegtk/AddOtherTestdrivegtkDialog.py:135
msgid "Please insert a Description"
msgstr "Nem adott meg leírást"

#: ../testdrivegtk/AddOtherTestdrivegtkDialog.py:140
msgid "Please insert a URL"
msgstr "Adjon meg elérési címet (URL)"

#: ../testdrivegtk/AddOtherTestdrivegtkDialog.py:171
msgid "No sync protocol has been selected, please select one."
msgstr ""
"Nincs szinkronizáló protokoll kiválasztva, a folytatáshoz válasszon egyet."

#: ../testdrivegtk/AddOtherTestdrivegtkDialog.py:196
msgid "Description"
msgstr "Leírás"

#: ../testdrivegtk/AddOtherTestdrivegtkDialog.py:227
msgid "Select Protocol:"
msgstr "Protokoll választás:"

#: ../testdrivegtk/PreferencesTestdrivegtkDialog.py:36
#: ../testdrivegtk/PreferencesTestdrivegtkDialog.py:37
msgid "Other..."
msgstr "Egyéb…"

#: ../testdrivegtk/PreferencesTestdrivegtkDialog.py:72
msgid "TestDrive Preferences"
msgstr "TestDrive beállítások"

#: ../testdrivegtk/PreferencesTestdrivegtkDialog.py:98
msgid "finish_initialization()"
msgstr "finish_initialization()"

#: ../testdrivegtk/PreferencesTestdrivegtkDialog.py:138
msgid "Select Repository:"
msgstr "Tároló kiválasztása:"

#: ../testdrivegtk/PreferencesTestdrivegtkDialog.py:149
#: ../testdrivegtk/PreferencesTestdrivegtkDialog.py:490
msgid "Select Release:"
msgstr "Kiadás kiválasztása:"

#. Load config files for local variables
#. self.load_config_files(file)
#: ../testdrivegtk/PreferencesTestdrivegtkDialog.py:217
#, python-format
msgid "Reading config file: [%s]"
msgstr "Konfiguráció beolvasása: [%s]"

#: ../testdrivegtk/PreferencesTestdrivegtkDialog.py:219
#, python-format
msgid "Unable to load config file [%s]"
msgstr "Konfiguráció beolvasása sikertelen: [%s]"

#: ../testdrivegtk/PreferencesTestdrivegtkDialog.py:276
#, python-format
msgid " of %s available."
msgstr " a(z) %s elérhetőből"

#: ../testdrivegtk/PreferencesTestdrivegtkDialog.py:337
#, python-format
msgid "Could not obtain the Ubuntu ISO list from %s..."
msgstr ""
"Az Ubuntu-lemezképek listájának letöltése sikertelen a következő helyről: %s…"

#: ../testdrivegtk/PreferencesTestdrivegtkDialog.py:341
msgid "Updating the Ubuntu ISO list cache..."
msgstr "Az Ubuntu-lemezkép lista gyorsítótárának frissítése…"

#: ../testdrivegtk/PreferencesTestdrivegtkDialog.py:349
msgid "get_preferences()"
msgstr "get_preferences()"

#: ../testdrivegtk/PreferencesTestdrivegtkDialog.py:472
#, python-format
msgid "Unable to clean up files from [%s]"
msgstr "A megadott helyről nem sikerült eltávolítani a fájlokat: [%s]"
