
def exception_callback(ex):
    print ex
